language: ruby
sudo: false
dist: xenial
cache: bundler
script:
  - gem install jekyll
  - bundle update
  - bundle install
  - bundle exec jekyll build -d public
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master # Commit to master instead of gh-pages
  github-token: $GH_TOKEN
  keep-history: true # By default, Travis uses push --force and wipes out commit history
  verbose: true
  on:
    branch: master
